import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { BookOpen, CalendarDays, Clock, Table2, UserCheck } from "lucide-react";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { StatCard, EmptyState } from "@/components/common/StatCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useStore } from "@/store/app-store";
import { periodLabel, sortByPeriod, todayName } from "@/lib/schedule-utils";

export const Route = createFileRoute("/faculty/")({
  head: () => ({
    meta: [
      { title: "Faculty Dashboard — ClassSync" },
      { name: "description", content: "Faculty personal timetable and teaching schedule overview." },
    ],
  }),
  component: FacultyDashboardPage,
});

function FacultyDashboardPage() {
  const store = useStore();
  const { user, timetable, subjects, sections, rooms, settings, faculty } = store;

  const currentFaculty = useMemo(
    () => faculty.find((f) => f.id === user?.facultyId) ?? faculty[0],
    [faculty, user],
  );

  const myClasses = useMemo(() => {
    if (!timetable || !currentFaculty) return [];
    return timetable.classes.filter((c) => c.facultyId === currentFaculty.id);
  }, [timetable, currentFaculty]);

  const mySubjects = useMemo(() => {
    if (!currentFaculty) return [];
    return subjects.filter((s) => s.facultyId === currentFaculty.id);
  }, [subjects, currentFaculty]);

  const today = todayName();
  const todaysClasses = useMemo(
    () => myClasses.filter((c) => c.day === today).sort(sortByPeriod),
    [myClasses, today],
  );

  return (
    <DashboardShell
      role="faculty"
      title={`Welcome, ${currentFaculty?.name ?? user?.name ?? "Professor"}`}
      description={`${currentFaculty?.department ?? "Academic"} Department · ${settings.collegeName}`}
      actions={
        <Link to="/faculty/timetable">
          <Button>
            <Table2 className="size-4" /> View My Timetable
          </Button>
        </Link>
      }
    >
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Assigned Subjects"
          value={mySubjects.length}
          icon={<BookOpen className="size-5" />}
        />
        <StatCard
          label="Weekly Classes"
          value={myClasses.length}
          icon={<CalendarDays className="size-5" />}
        />
        <StatCard
          label="Classes Today"
          value={todaysClasses.length}
          tone={todaysClasses.length > 0 ? "accent" : "default"}
          icon={<Clock className="size-5" />}
        />
        <StatCard
          label="Max Load / Day"
          value={`${currentFaculty?.maxClassesPerDay ?? 4} periods`}
          icon={<UserCheck className="size-5" />}
        />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="text-base">Today's Schedule · {today}</CardTitle>
          </CardHeader>
          <CardContent>
            {todaysClasses.length === 0 ? (
              <EmptyState
                title="No classes scheduled for today"
                description={
                  timetable
                    ? "You have no teaching periods on this day."
                    : "Timetable has not been generated by the administrator yet."
                }
              />
            ) : (
              <div className="space-y-2">
                {todaysClasses.map((c) => {
                  const subject = subjects.find((s) => s.id === c.subjectId);
                  const section = sections.find((s) => s.id === c.sectionId);
                  const room = rooms.find((r) => r.id === c.roomId);
                  return (
                    <div
                      key={c.id}
                      className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-border p-3"
                    >
                      <div>
                        <p className="text-sm font-semibold">{subject?.name}</p>
                        <p className="text-xs text-muted-foreground">
                          Section: {section?.name} ({section?.course}) · Room {room?.number} (
                          {room?.building})
                        </p>
                      </div>
                      <span className="rounded bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">
                        {periodLabel(settings, c.period)}
                        {c.duration === 2 ? " (2 hrs)" : ""}
                      </span>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">Assigned Subjects</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {mySubjects.length === 0 ? (
              <p className="text-sm text-muted-foreground">No subjects assigned.</p>
            ) : (
              mySubjects.map((s) => (
                <div
                  key={s.id}
                  className="rounded-md border border-border p-3 text-sm"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-semibold">{s.name}</span>
                    <span className="text-xs text-muted-foreground">{s.code}</span>
                  </div>
                  <div className="mt-1 flex items-center justify-between text-xs text-muted-foreground">
                    <span>{s.type === "lab" ? "Practical (Lab)" : "Theory"}</span>
                    <span>{s.classesPerWeek} classes/wk · {s.credits} credits</span>
                  </div>
                </div>
              ))
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardShell>
  );
}

