import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { EmptyState } from "@/components/common/StatCard";
import { TimetableGrid } from "@/components/timetable/TimetableGrid";
import { useStore } from "@/store/app-store";
import { coversPeriod } from "@/lib/schedule-utils";

export const Route = createFileRoute("/student/timetable")({
  head: () => ({
    meta: [
      { title: "My Timetable — Student — ClassSync" },
      { name: "description", content: "Section weekly class timetable." },
    ],
  }),
  component: StudentTimetablePage,
});

function StudentTimetablePage() {
  const store = useStore();
  const { user, timetable, settings, sections } = store;

  const currentSection = useMemo(
    () => sections.find((s) => s.id === user?.sectionId) ?? sections[0],
    [sections, user],
  );

  const sectionClasses = useMemo(() => {
    if (!timetable || !currentSection) return [];
    return timetable.classes.filter((c) => c.sectionId === currentSection.id);
  }, [timetable, currentSection]);

  const columns = settings.workingDays.map((d) => ({ id: d, label: d }));

  const getClasses = (day: string, period: number) =>
    sectionClasses.filter((c) => c.day === day && coversPeriod(c, period));

  return (
    <DashboardShell
      role="student"
      title="Section Timetable"
      description={`Weekly class schedule for Section ${currentSection?.name ?? "CSE-A"} (${currentSection?.course ?? "B.Tech"})`}
    >
      {!timetable ? (
        <EmptyState
          title="No Timetable Generated"
          description="The institutional timetable has not been generated by the administrator yet."
        />
      ) : (
        <div className="space-y-4">
          <TimetableGrid columns={columns} getClasses={getClasses} />
        </div>
      )}
    </DashboardShell>
  );
}

