import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { EmptyState } from "@/components/common/StatCard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useStore } from "@/store/app-store";
import { periodLabel, sortByPeriod, todayName } from "@/lib/schedule-utils";

export const Route = createFileRoute("/student/today")({
  head: () => ({
    meta: [
      { title: "Today's Classes — Student — ClassSync" },
      { name: "description", content: "Schedule of classes and lab venues for today." },
    ],
  }),
  component: StudentTodayPage,
});

function StudentTodayPage() {
  const { user, timetable, sections, subjects, rooms, faculty, settings } = useStore();

  const currentSection = useMemo(
    () => sections.find((s) => s.id === user?.sectionId) ?? sections[0],
    [sections, user],
  );

  const today = todayName();

  const todaysClasses = useMemo(() => {
    if (!timetable || !currentSection) return [];
    return timetable.classes
      .filter((c) => c.sectionId === currentSection.id && c.day === today)
      .sort(sortByPeriod);
  }, [timetable, currentSection, today]);

  return (
    <DashboardShell
      role="student"
      title={`Today's Classes · ${today}`}
      description={`Daily timetable and classroom locations for ${currentSection?.name ?? "Section"}`}
    >
      {!timetable || todaysClasses.length === 0 ? (
        <EmptyState
          title="No classes scheduled for today"
          description={
            timetable
              ? "You have no lectures or practical sessions scheduled on this day."
              : "Timetable has not been generated by the administrator yet."
          }
        />
      ) : (
        <div className="space-y-4">
          {todaysClasses.map((c) => {
            const sub = subjects.find((s) => s.id === c.subjectId);
            const fac = faculty.find((f) => f.id === c.facultyId);
            const rm = rooms.find((r) => r.id === c.roomId);
            const isLab = sub?.type === "lab";
            return (
              <Card key={c.id} className={isLab ? "border-accent/40 bg-accent/5" : ""}>
                <CardHeader className="pb-2">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <CardTitle className="text-base">{sub?.name}</CardTitle>
                    <span className="rounded bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">
                      {periodLabel(settings, c.period)}
                      {c.duration === 2 ? " (2 Hours)" : ""}
                    </span>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2 text-xs text-muted-foreground sm:grid-cols-3">
                    <div>
                      <span className="font-semibold text-foreground">Course:</span> {sub?.code} ({sub?.type})
                    </div>
                    <div>
                      <span className="font-semibold text-foreground">Instructor:</span> {fac?.name}
                    </div>
                    <div>
                      <span className="font-semibold text-foreground">Location:</span> Room {rm?.number} ({rm?.building}, Floor {rm?.floor})
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </DashboardShell>
  );
}

